version: "3.8"
services:
  frontend1:
    image: bastianolea/2025tingeson1-frontend:latest
    networks:
      - frontend-network

  frontend2:
    image: bastianolea/2025tingeson1-frontend:latest
    networks:
      - frontend-network

  frontend3:
    image: bastianolea/2025tingeson1-frontend:latest
    networks:
      - frontend-network

  backend1:
    image: bastianolea/2025tingeson1-backend:latest
    environment:
      - DB_HOST=db  # Usa el nombre del servicio en lugar de una IP fija
    networks:
      - backend-network

  backend2:
    image: bastianolea/2025tingeson1-backend:latest
    environment:
      - DB_HOST=db  # Usa el nombre del servicio en lugar de una IP fija
    networks:
      - backend-network

  backend3:
    image: bastianolea/2025tingeson1-backend:latest
    environment:
      - DB_HOST=db  # Usa el nombre del servicio en lugar de una IP fija
    networks:
      - backend-network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass1234?
      MYSQL_DATABASE: kartingrm
      MYSQL_USER: root
      MYSQL_PASSWORD: pass1234?
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx-frontend:
    image: nginx:latest
    ports:
      - "5173:80"
    volumes:
      - ./nginx-kartingrm-frontend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  nginx-backend:
    image: nginx:latest
    ports:
      - "8050:8050"
    volumes:
      - ./nginx-kartingrm-backend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:

volumes:
  db_data: