version: "3.8"
services:
  frontend1:
    image: bastianolea/2025tingeson1-frontend:latest
    networks:
      - frontend-network

  frontend2:
    image: bastianolea/2025tingeson1-frontend:latest
    networks:
      - frontend-network

  frontend3:
    image: bastianolea/2025tingeson1-frontend:latest
    networks:
      - frontend-network

  backend1:
    image: bastianolea/2025tingeson1-backend:latest
    environment:
      - DB_HOST=host.docker.internal  # Conexión al host local desde Docker
      - DB_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/kartingrm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass1234?
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - backend-network

  backend2:
    image: bastianolea/2025tingeson1-backend:latest
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/kartingrm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass1234?
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - backend-network

  backend3:
    image: bastianolea/2025tingeson1-backend:latest
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/kartingrm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass1234?
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - backend-network

  nginx-frontend:
    image: nginx:latest
    ports:
      - "5173:80"
    volumes:
      - ./nginx-kartingrm-frontend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  nginx-backend:
    image: nginx:latest
    ports:
      - "8100:8100"
    volumes:
      - ./nginx-kartingrm-backend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:
